/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "Stm32F103C8T6.h"

#include "RCC_Interface.h"
#include "GPIO_Interface.h"
#include "SYSTICK_interface.h"

#include "SevenSeg_Interface.h"



SevSegConfigs_t SevenSeg1 =
{
							.DigA_port = PORTA,
							.DigA_pin = PIN11,
							.DigB_port = PORTA,
							.DigB_pin = PIN8,
							.DigC_port = PORTB,
							.DigC_pin = PIN15,
							.DigD_port = PORTB,
							.DigD_pin = PIN14,
							.DigE_port = PORTB,
							.DigE_pin = PIN13,
							.DigF_port = PORTB,
							.DigF_pin = PIN12,
							.DigG_port = PORTA,
							.DigG_pin = PIN12,
							.DigDot_port = PORTA,
							.DigDot_pin = PIN15,

							.ControlPin_port = PORTB,
							.ControlPin_pin = PIN8,

							.commonType = CommonCathodeDrivenByBJT

};


SevSegConfigs_t SevenSeg2 =
{
							.DigA_port = PORTA,
							.DigA_pin = PIN11,
							.DigB_port = PORTA,
							.DigB_pin = PIN8,
							.DigC_port = PORTB,
							.DigC_pin = PIN15,
							.DigD_port = PORTB,
							.DigD_pin = PIN14,
							.DigE_port = PORTB,
							.DigE_pin = PIN13,
							.DigF_port = PORTB,
							.DigF_pin = PIN12,
							.DigG_port = PORTA,
							.DigG_pin = PIN12,
							.DigDot_port = PORTA,
							.DigDot_pin = PIN15,

							.ControlPin_port = PORTB,
							.ControlPin_pin = PIN9,

							.commonType = CommonCathodeDrivenByBJT


};


SevSegConfigs_t SevenSeg3 =
{
							.DigA_port = PORTA,
							.DigA_pin = PIN11,
							.DigB_port = PORTA,
							.DigB_pin = PIN8,
							.DigC_port = PORTB,
							.DigC_pin = PIN15,
							.DigD_port = PORTB,
							.DigD_pin = PIN14,
							.DigE_port = PORTB,
							.DigE_pin = PIN13,
							.DigF_port = PORTB,
							.DigF_pin = PIN12,
							.DigG_port = PORTA,
							.DigG_pin = PIN12,
							.DigDot_port = PORTA,
							.DigDot_pin = PIN15,

							.ControlPin_port = PORTB,
							.ControlPin_pin = PIN3,

							.commonType = CommonCathodeDrivenByBJT


};


int main(void)
{
	int DisplayNum = 987;

	RCC_SetSysClk(HSI);
	RCC_SetClkStatus(HSI, ON);

	RCC_APB2EnableClk(APB2_GPIOA);
	RCC_APB2EnableClk(APB2_GPIOB);

	SevSeg_Init((const SevSegConfigs_t *) &SevenSeg1);
	SevSeg_Init((const SevSegConfigs_t *) &SevenSeg2);
	SevSeg_Init((const SevSegConfigs_t *) &SevenSeg3);




    /* Loop forever */
	for(;;)
	{
		/*for(int8_t i = 9; i >= 0; i--)
			{
				SevSeg_DisplayNum(&SevenSeg1, i);
				SevSeg_PowerState(&SevenSeg1, PowerOn);
				SYSTICK_DelayMs(1000);
				SevSeg_PowerState(&SevenSeg1, PowerOff);
				SYSTICK_DelayMs(1000);
			}*/



			/*SevSeg_DisplayNum(&SevenSeg1, DisplayNum/10);
			SevSeg_PowerState(&SevenSeg1, PowerOn);
			SYSTICK_DelayMs(10);
			SevSeg_PowerState(&SevenSeg1, PowerOff);
			SevSeg_DisplayNum(&SevenSeg2, DisplayNum%10);
			SevSeg_PowerState(&SevenSeg2, PowerOn);
			SYSTICK_DelayMs(10);
			SevSeg_PowerState(&SevenSeg2, PowerOff);*/


		/*1st digit*/
					SevSeg_DisplayNum(&SevenSeg1, DisplayNum/100);
					SevSeg_PowerState(&SevenSeg1, PowerOn);
					SYSTICK_DelayMs(5);
					SevSeg_PowerState(&SevenSeg1, PowerOff);

					/*2nd digit*/
					SevSeg_DisplayNum(&SevenSeg2, (DisplayNum%100)/10);
					SevSeg_PowerState(&SevenSeg2, PowerOn);
					SYSTICK_DelayMs(5);
					SevSeg_PowerState(&SevenSeg2, PowerOff);

					/*3rd digit*/
					SevSeg_DisplayNum(&SevenSeg3, (DisplayNum%10));
					SevSeg_PowerState(&SevenSeg3, PowerOn);
					SYSTICK_DelayMs(5);
					SevSeg_PowerState(&SevenSeg3, PowerOff);


//					SYSTICK_DelayMs(5000);
//
//		for(int16_t i = 999; i >= 0; i--)
//		{
//			/*1st digit*/
//			SevSeg_DisplayNum(&SevenSeg1, i/100);
//			SevSeg_PowerState(&SevenSeg1, PowerOn);
//			SYSTICK_DelayMs(10);
//			SevSeg_PowerState(&SevenSeg1, PowerOff);
//
//			/*2nd digit*/
//			SevSeg_DisplayNum(&SevenSeg2, (i%100)/10);
//			SevSeg_PowerState(&SevenSeg2, PowerOn);
//			SYSTICK_DelayMs(10);
//			SevSeg_PowerState(&SevenSeg2, PowerOff);
//
//			/*3rd digit*/
//			SevSeg_DisplayNum(&SevenSeg3, (i%100));
//			SevSeg_PowerState(&SevenSeg3, PowerOn);
//			SYSTICK_DelayMs(10);
//			SevSeg_PowerState(&SevenSeg3, PowerOff);





		}












}




